import 'package:flutter/material.dart';
import 'package:ihe/commons/colors.dart';

class MyTruck extends StatefulWidget {
  @override
  _MyTruckState createState() => _MyTruckState();
}

class _MyTruckState extends State<MyTruck> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: myRed,
        title: Text('Vehicle Details',style: TextStyle(color: Colors.white),),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.horizontal, // To enable horizontal scrolling
        child: SingleChildScrollView(
          child: DataTable(
            columns: const [
              DataColumn(label: Text('Vehicle ID')),
              DataColumn(label: Text('Owner Name')),
              DataColumn(label: Text('Qatar ID')),
              DataColumn(label: Text('License Plate')),
              DataColumn(label: Text('Make')),
              DataColumn(label: Text('Model')),
              DataColumn(label: Text('Year')),
              DataColumn(label: Text('Chassis No')),
              DataColumn(label: Text('Engine No')),
              DataColumn(label: Text('Fuel Type')),
              DataColumn(label: Text('Registration Date')),
              DataColumn(label: Text('Insurance Company')),
              DataColumn(label: Text('Policy No')),
              DataColumn(label: Text('Insurance Expiry')),
              DataColumn(label: Text('Color')),
              DataColumn(label: Text('Type')),
              DataColumn(label: Text('Reg Expiry')),
              DataColumn(label: Text('Inspection Date')),
              DataColumn(label: Text('Loan/Lease Status')),
              DataColumn(label: Text('Branch')),
              DataColumn(label: Text('Remarks')),
            ],
            rows: [
              DataRow(cells: [
                DataCell(Text('V001')),
                DataCell(Text('Ahmed Ali')),
                DataCell(Text('12345678901')),
                DataCell(Text('Q12345')),
                DataCell(Text('Toyota')),
                DataCell(Text('Camry')),
                DataCell(Text('2018')),
                DataCell(Text('ABC1234XYZ')),
                DataCell(Text('ENG12345')),
                DataCell(Text('Petrol')),
                DataCell(Text('01-01-2019')),
                DataCell(Text('Qatar Ins. Co.')),
                DataCell(Text('POL12345')),
                DataCell(Text('01-01-2024')),
                DataCell(Text('White')),
                DataCell(Text('Private')),
                DataCell(Text('01-01-2025')),
                DataCell(Text('01-01-2024')),
                DataCell(Text('None')),
                DataCell(Text('Doha Branch')),
                DataCell(Text('No remarks')),
              ]),
              DataRow(cells: [
                DataCell(Text('V002')),
                DataCell(Text('Sara Noor')),
                DataCell(Text('23456789012')),
                DataCell(Text('Q56789')),
                DataCell(Text('Honda')),
                DataCell(Text('Civic')),
                DataCell(Text('2020')),
                DataCell(Text('DEF5678XYZ')),
                DataCell(Text('ENG67890')),
                DataCell(Text('Diesel')),
                DataCell(Text('15-03-2020')),
                DataCell(Text('Qatar Nat. Ins.')),
                DataCell(Text('POL67890')),
                DataCell(Text('15-03-2025')),
                DataCell(Text('Blue')),
                DataCell(Text('Private')),
                DataCell(Text('15-03-2026')),
                DataCell(Text('15-03-2025')),
                DataCell(Text('None')),
                DataCell(Text('Al Khor Branch')),
                DataCell(Text('Leased Vehicle')),
              ]),
              DataRow(cells: [
                DataCell(Text('V003')),
                DataCell(Text('Mohammed Saif')),
                DataCell(Text('34567890123')),
                DataCell(Text('Q67890')),
                DataCell(Text('Nissan')),
                DataCell(Text('Altima')),
                DataCell(Text('2019')),
                DataCell(Text('GHI9012XYZ')),
                DataCell(Text('ENG90123')),
                DataCell(Text('Petrol')),
                DataCell(Text('01-06-2019')),
                DataCell(Text('Doha Ins.')),
                DataCell(Text('POL90123')),
                DataCell(Text('01-06-2024')),
                DataCell(Text('Black')),
                DataCell(Text('Commercial')),
                DataCell(Text('01-06-2025')),
                DataCell(Text('01-06-2024')),
                DataCell(Text('Loaned')),
                DataCell(Text('Doha Branch')),
                DataCell(Text('Service Due Soon')),
              ]),
              DataRow(cells: [
                DataCell(Text('V004')),
                DataCell(Text('Fatima Khalid')),
                DataCell(Text('45678901234')),
                DataCell(Text('Q34567')),
                DataCell(Text('Tesla')),
                DataCell(Text('Model S')),
                DataCell(Text('2021')),
                DataCell(Text('JKL3456XYZ')),
                DataCell(Text('ENG34567')),
                DataCell(Text('Electric')),
                DataCell(Text('01-08-2021')),
                DataCell(Text('Al Koot Ins.')),
                DataCell(Text('POL34567')),
                DataCell(Text('01-08-2026')),
                DataCell(Text('Red')),
                DataCell(Text('Private')),
                DataCell(Text('01-08-2027')),
                DataCell(Text('01-08-2026')),
                DataCell(Text('None')),
                DataCell(Text('Wakrah Branch')),
                DataCell(Text('Electric Vehicle')),
              ]),
              DataRow(cells: [
                DataCell(Text('V005')),
                DataCell(Text('Omar Hassan')),
                DataCell(Text('56789012345')),
                DataCell(Text('Q23456')),
                DataCell(Text('Ford')),
                DataCell(Text('F-150')),
                DataCell(Text('2022')),
                DataCell(Text('MNO2345XYZ')),
                DataCell(Text('ENG23456')),
                DataCell(Text('Diesel')),
                DataCell(Text('12-12-2022')),
                DataCell(Text('Qatar Ins. Co.')),
                DataCell(Text('POL23456')),
                DataCell(Text('12-12-2027')),
                DataCell(Text('Gray')),
                DataCell(Text('Commercial')),
                DataCell(Text('12-12-2028')),
                DataCell(Text('12-12-2027')),
                DataCell(Text('None')),
                DataCell(Text('Al Rayyan Branch')),
                DataCell(Text('New Vehicle')),
              ]),
              DataRow(cells: [
                DataCell(Text('V006')),
                DataCell(Text('Yousef Salem')),
                DataCell(Text('67890123456')),
                DataCell(Text('Q09876')),
                DataCell(Text('BMW')),
                DataCell(Text('X5')),
                DataCell(Text('2017')),
                DataCell(Text('PQR5678XYZ')),
                DataCell(Text('ENG56789')),
                DataCell(Text('Petrol')),
                DataCell(Text('22-05-2017')),
                DataCell(Text('Doha Ins.')),
                DataCell(Text('POL56789')),
                DataCell(Text('22-05-2022')),
                DataCell(Text('Silver')),
                DataCell(Text('Private')),
                DataCell(Text('22-05-2023')),
                DataCell(Text('22-05-2022')),
                DataCell(Text('Loaned')),
                DataCell(Text('Doha Branch')),
                DataCell(Text('Loan ends in 1 year')),
              ]),
            ],
          ),
        ),
      ),
    );
  }
}

